//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMensajes
    {
        public int idMensaje { get; set; }
        public int fkCliente { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string Mensaje { get; set; }
        public string Respuesta { get; set; }
        public int Estado { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
    }
}
