//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPoliDeportivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPoliDeportivo()
        {
            this.tblCalendarioAtencion = new HashSet<tblCalendarioAtencion>();
            this.tblCancha = new HashSet<tblCancha>();
        }
    
        public int idPoliDeportivo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public string Telefono { get; set; }
        public bool Abierto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCalendarioAtencion> tblCalendarioAtencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCancha> tblCancha { get; set; }
    }
}
