//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_EnviarMensaje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCuentaUsuario
    {
        public int idCuentaUsuario { get; set; }
        public int fkPersona { get; set; }
        public Nullable<int> TipoUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Estado { get; set; }
    
        public virtual tblPersona tblPersona { get; set; }
    }
}
