//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_EnviarMensaje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPago
    {
        public int idPago { get; set; }
        public int fkReserva { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
        public decimal Monto { get; set; }
    
        public virtual tblReserva tblReserva { get; set; }
    }
}
