//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDia
    {
        public tblDia()
        {
            this.tblHorarioAtencion = new HashSet<tblHorarioAtencion>();
        }
    
        public int idDia { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<tblHorarioAtencion> tblHorarioAtencion { get; set; }
    }
}
