//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetallePago
    {
        public int idDetallePago { get; set; }
        public int fkPago { get; set; }
        public int fkServicios { get; set; }
        public int TipoServicio { get; set; }
        public int Cantidad { get; set; }
    
        public virtual tblPago tblPago { get; set; }
        public virtual tblServicios tblServicios { get; set; }
    }
}
