//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHora
    {
        public tblHora()
        {
            this.tblHorarioAtencion = new HashSet<tblHorarioAtencion>();
        }
    
        public int idHora { get; set; }
        public System.TimeSpan Apertura { get; set; }
        public System.TimeSpan Cierre { get; set; }
    
        public virtual ICollection<tblHorarioAtencion> tblHorarioAtencion { get; set; }
    }
}
