//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPoliDeportivo
    {
        public tblPoliDeportivo()
        {
            this.tblCancha = new HashSet<tblCancha>();
            this.tblHorarioAtencion = new HashSet<tblHorarioAtencion>();
        }
    
        public int idPoliDeportivo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public System.Data.Spatial.DbGeography Ubicacion { get; set; }
        public string Telefono { get; set; }
        public bool Abierto { get; set; }
    
        public virtual ICollection<tblCancha> tblCancha { get; set; }
        public virtual ICollection<tblHorarioAtencion> tblHorarioAtencion { get; set; }
    }
}
