//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPago
    {
        public tblPago()
        {
            this.tblDetallePago = new HashSet<tblDetallePago>();
        }
    
        public int idPago { get; set; }
        public int fkCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> TotalPagado { get; set; }
        public int fkReserva { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual ICollection<tblDetallePago> tblDetallePago { get; set; }
    }
}
