//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServicios
    {
        public tblServicios()
        {
            this.tblDetallePago = new HashSet<tblDetallePago>();
        }
    
        public int idServicios { get; set; }
        public string Detalle { get; set; }
        public decimal Precio { get; set; }
        public int Disponibilidad { get; set; }
    
        public virtual ICollection<tblDetallePago> tblDetallePago { get; set; }
    }
}
